### ISSUE TITLE
Sending to an integrated address asks to accept transfer to a unfamiliar address

### ISSUE THREAD

**Issue by tficharmers** [LedgerHQ/app-monero#19]
I've just tried sending some XMR to an integrated address and when asked to confirm the amount to send to the receiving address, the address shown on the Ledger Nano isn't the integrated address, but the standard Monero address that makes up the integrated address + the Payment ID. I split the integrated address to check it here:

https://xmr.llcoins.net/addresstests.html

So whilst the XMR would end up at the right place if I had gone through with the transaction, this would be confusing for some users as the address they put into the CLI/GUI would be different to the one displayed on the Ledger Nano. I would suspect some would think this was broken. I think the Ledger Nano should display the Integrated address.

I suppose another concern would be that if the Ledger is appearing to strip the Payment ID from the Integrated address on the device, will the CLI/GUI send the Payment ID with the transaction? I suspect the CLI/GUI will send the payment ID, but I didn't test this due to the issue in the next paragraph.

I didn't actually go through with the transaction because of something else that I think this is related to issue #15. The transaction was creating a non-insignificant amount of change and was asking me to accept sending it to an address that was unfamiliar. This is perhaps a bigger issue, but there was no way I was going to test losing that amount of change into the abyss!

**Comment by gabrieldov** [comment]
Ledger Nano should display the Integrated address as stated above. Very bad user experience for user, since the screen is supposed to be the last check before sweeping all your funds and you want to see the address you input appearing for confirmation.

**Comment by tibo33** [comment]
Same here, when churning to primary address or to subaddress I get following:

1. I send all to primary address in gui wallet
2. ledger shows fee --> I accept fee
3. ledger shows amount 0 and shows different destination address, asks to accept TX --> at this point I just reject the tx, since churning is the total wallet amount I don't want to 'risk' sending it to another address.

thanks for looking into it

**Comment by jonathancross** [comment]
Hi @cslashm , can you please elaborate -- are you saying that Integrated address are **_not supported_** by  Ledger devices?
