### ISSUE TITLE
Error: failed to generate new wallet: Wrong Device Status : SW=6930 (EXPECT=9000, MASK=ffff)

### ISSUE THREAD

**Issue by Jay991** [LedgerHQ/app-monero#47]
Hi I'm running on monero-gui-v0.15.0.1
OS: Ubuntu 19.10
Updated the lastest ledger app and Monero App on ledger nano s
Also enabled developer mode on Ledger Live 
Still receiving this error when attempting to connect my wallet:
`Error: failed to generate new wallet: Wrong Device Status : SW=6930 (EXPECT=9000, MASK=ffff`)

**Comment by pricead** [comment]
Make sure you have the Ledger Monero app version 1.4.2 on your device

**Comment by cslashm** [comment]
check and provide your firm version and app version.

**Comment by grydz** [comment]
I'm closing the issue.

Feel free to open a new one if it doesn't work with Monero app `1.6.0` and Monero client `0.16.0.0`.

**Comment by infa-jowoods** [comment]
New client is working great thanks @grydz - I see there is now parity with Nano S & X versioning.

Nice work.
