### ISSUE TITLE
Wallet address not being displayed properly on ledger device

### ISSUE THREAD

**Issue by qwert95** [LedgerHQ/app-monero#49]
I'm running the latest firmware for my nano x and the last app version.  
If i open the monero app i get a page with the monero logo and the first and last characters of my address.
If then i press both buttons and go right few times I can see the complete address, except that on page 2/2 it's not showing the same ending but rather some of the last characters are cut out.

**Comment by russoj88** [comment]
I have the same issue on the Nano S.
Ledger v1.6.0
Monero App v1.4.2

I see address characters 1-33, and 46-94, but not 34-45.

**Comment by pricead** [comment]
I've seen the same issue for a while with a device configured with one seed, but the issue doesn't occur when using another seed. So some kind of parsing issue when displaying certain addresses, but not with all of them.

**Comment by cslashm** [comment]
@qwert95, it's just missing some char at end but all the other are right, true?

**Comment by qwert95** [comment]
Yes, all the other characters match the ones I see from monero-gui client
when i connect my ledger

Il Gio 12 Dic 2019, 14:29 Cédric <notifications@github.com> ha scritto:

**Comment by MrClottom** [comment]
I'm having a similar problem on my nano ledger s with certain addresses where certain letters of the address aren't matching but most of the address is. Using the following [repl](https://repl.it/repls/ExpensiveGruesomeBrace) I have reproduced/isolated the error, it may or may not be the same bug as the others I will submit a solution shortly

**Comment by MrClottom** [comment]
This [pull request](https://github.com/LedgerHQ/app-monero/pull/57) should fix it

**Comment by cslashm** [comment]
Thanks for having analyze the problem and propose a  PR.
I check that during the coming day.

**Comment by grydz** [comment]
PR https://github.com/LedgerHQ/app-monero/pull/57 merged.
