### ISSUE TITLE
v0.16.0.0 will release in a couple of days

### ISSUE THREAD

**Issue by selsta** [LedgerHQ/app-monero#58]
Just a reminder to get the Monero App Ledger ready for the update.

Corresponding branch: https://github.com/monero-project/monero/tree/release-v0.16

No hard fork. We aim to release in ~5-6 days.

**Comment by selsta** [comment]
Ping @niooss-ledger @cslashm 

It would be good to have confirmation that no additional PR is required to make Ledger work with v0.16 so that we can tag.

**Comment by cslashm** [comment]
@niooss-ledger is on the deck if I correctly understand

**Comment by selsta** [comment]
On the deck?

**Comment by niooss-ledger** [comment]
Not exactly. My task for now is to check whether the Monero application contains other security issues than the one that have been published. So I spent quite some time trying to understand it. It happens that I found some non-security "bugs" (and minor issues) on the way so I have set up a development environment, opened some very simple Pull Requests, massively updated the documentation...

A person from another Ledger team has been identified to test the application and Monero Client and I will help this coworker on this task.

**Comment by cslashm** [comment]
So nice you are on the right way. Let's say you check it for 0.16.

**Comment by selsta** [comment]
We will release v0.16.0.0 CLI today or tomorrow. Any updates on a new Ledger app version that supports this release?

**Comment by cslashm** [comment]
App was under revalidation this last days if I correctly understood.
@niooss-ledger, any info?

**Comment by johnalanwoods** [comment]
Any update on this @niooss-ledger @cslashm ?

**Comment by grydz** [comment]
I'm the one testing the monero app with monero client `v0.16.0.0` but I've encountered some bugs.

As soon as they're fixed, I'll release monero app `1.6.0` with support for monero client `v0.16.0.0`.

**Comment by cslashm** [comment]
We (Francois @grydz ) just spot  an issue. We are on.

**Comment by grydz** [comment]
We're just waiting https://github.com/monero-project/monero/pull/6597 and https://github.com/monero-project/monero/pull/6597 to be merged and it should be good.

**Comment by selsta** [comment]
@grydz I don’t think we will immediately release v0.16.0.1... Transferring to a single address should be good? Are there problems I can’t think of?

**Comment by pricead** [comment]
Are you going to fix issue #49 in this release? I see that there is a pull request that supposedly fixes that issue too.

**Comment by grydz** [comment]
Yes I will, I just can't reproduce the issue...

**Comment by selsta** [comment]
> locked_transfer are also not working.

Both of these are rarely used features. We will include the fix in the next version which will probably come out in a couple weeks.

**Comment by grydz** [comment]
> > locked_transfer are also not working.
> 
> Both of these are rarely used features. We will include the fix in the next version which will probably come out in 2-3 weeks. Can you at least add a v0.16 compatible version to the dev mode inside Ledger Live in the meantime?

That would be possible. When do you plan to release the GUI Monero Wallet version `0.16.0.0`?

**Comment by selsta** [comment]
Today.

**Comment by selsta** [comment]
@grydz GUI v0.16 is now released.

**Comment by victorleaning** [comment]
When will the ledger version come out? It's quite annoying how Ledger has to interact with Monero.

**Comment by grydz** [comment]
> @grydz GUI v0.16 is now released.

Great, we will release the Monero application `1.6.0` in the next few days.

**Comment by lacksfish** [comment]
v0.16.0.0 is released, can't wait for Monero Ledger app 1.6.0 to roll out :tada:

**Comment by victorleaning** [comment]
> 
> 
> > > locked_transfer are also not working.
> > 
> > 
> > Both of these are rarely used features. We will include the fix in the next version which will probably come out in 2-3 weeks. Can you at least add a v0.16 compatible version to the dev mode inside Ledger Live in the meantime?
> 
> That would be possible. When do you plan to release the GUI Monero Wallet version `0.16.0.0`?

Not to sound pushy but it's been 22 days since you guys to the notification...

**Comment by cslashm** [comment]
@victorleaning you are welcome to help

**Comment by pricead** [comment]
> @victorleaning you are welcome to help

This seems a bit snarky. Unless Victor works for Ledger as well, I don't see what sort of help he can provide that would get the app deployed in the Ledger Live Manager now.

I don't think it's too much to ask for Ledger to do a better job keeping up with the official Monero GUI/CLI releases either, especially because the lack of an updated XMR device app effectively prevents users running the latest desktop app from accessing their funds.

**Comment by johnalanwoods** [comment]
Precisely. Which will lead to diminished sales. Supporting Monero is not doing us a favour. It’s supporting a major cryptocurrency for a good business reason.

**Comment by lacksfish** [comment]
Well anyone can still use Monero v0.15.0.x and everything is working fine. It's not like funds are inaccessible right now, so people should sit back and take a chill pill.

Ledger devs are doing outstanding work and I can easily wait another few days before using the v0.16 of Monero. It's not that big of a deal... some people just like to be angry.

**Comment by victorleaning** [comment]
> 
> 
> Well anyone can still use Monero v0.15.0.x and everything is working fine. It's not like funds are inaccessible right now, so people should sit back and take a chill pill.
> 
> Ledger devs are doing outstanding work and I can easily wait another few days before using the v0.16 of Monero. It's not that big of a deal... some people just like to be angry.

Funds are indeed not inaccessible, however there's many complaints by (newer) users who are unaware of the fact that Ledger doesn't support v0.16, I understand that development takes time ofcourse but it'd be nice if we atleast got a somewhat general notification somewhere that the app is on the way.

**Comment by selsta** [comment]
Ledger Monero app v1.6.0 seems to be out. Thanks @Ledger team :)
