### ISSUE TITLE
Error when trying to create transaction with too many inputs with device app version 1.6.0

### ISSUE THREAD

**Issue by jackfruit-data** [LedgerHQ/app-monero#62]
Installed the new version 1.6.0, and I tried to send a transaction today that would have required around ~~8~~ (actually, looking again I think it only had 4 or 5) inputs from my Ledger wallet's XMR balance. The transaction failed during the "Preparing TX" stage, with the error "Can't create transaction: unexpected error: Wrong Device Status: 0x6701 (UNKNOWN), EXPECTED 0x9000 (SW_OK), MASK 0xffff" on the desktop GUI. 

I later tried sending a smaller transaction that would have only required a couple inputs and the transaction went through OK. I seem to get errors when sending a transaction that needs more than 2 or 3 inputs. 

([posted about this on Reddit here](https://www.reddit.com/r/Monero/comments/gx3zqr/ledger_monero_app_160_now_available/fsz1lkl/))

**Comment by johnalanwoods** [comment]
Same issue. When seeing with approximately 6 inputs.

**Comment by grydz** [comment]
Unfortunately this is due to a bug in the Monero client `0.16.0.0` (see https://github.com/monero-project/monero/pull/6594). It will be fixed in a future release of the Monero CLI/GUI (`0.16.0.1`?).

**Comment by selsta** [comment]
We will wait a bit more to see if more bugs show up (not necessarily Ledger related) and then release v0.16.0.1.

**Comment by selsta** [comment]
v0.16.0.1 CLI is released, GUI is tagged and will be out in the next days.

**Comment by jackfruit-data** [comment]
I can confirm that this issue seems fixed with v0.16.0.1 CLI: I was able to send a transaction out of my Ledger wallet that previously failed.

**Comment by selsta** [comment]
Corresponding GUI including the fixed is ready and will be released today / tomorrow.
