### ISSUE TITLE
Ledger update for Monero- Problems with password for GUI.

### ISSUE THREAD

**Issue by polhung3** [LedgerHQ/app-monero#63]
Today I updated  Ledger Live and the Apps, incl. Monero, after that I cannot enter my GUI wallet. Its saying: Couldnot open wallet. Wrong device status: SW=6e00 (expect=9000, MASK=ffff). Was working perfect before the update. Anybody know what to do?

**Comment by pricead** [comment]
Did you also update the GUI to version: 0.16.0.0 (Nitrogen Nebula)?

**Comment by polhung3** [comment]
No I didnot, now it is working, thanks a lot, your the man!!
