### ISSUE TITLE
monero GUI WALLET error 0x6e00 (SW_CLA_NOT_SUPPOTED). EXPECTED (0x9000 (SW_OK),MASK 0xfff

### ISSUE THREAD

**Issue by Zed1976** [LedgerHQ/app-monero#64]
Hello 
i cannot open my GUI WALLET  linked to my Ledger NANO X.
i always have this error after enterring my password in GUI:
monero error 0x6e00 (SW_CLA_NOT_SUPPOTED). EXPECTED (0x9000 (SW_OK),MASK 0xfff

I use Monero apps on ledger 1.5.1
and GUI WALLET 0.16.0.0
Windows 10 x64  updated.

Please could you help me .. i ma afraid to loose all my coin .
Thank you

**Comment by pricead** [comment]
You need to update the Monero device app to 0.16 (via the Manager in Ledger Live).

**Comment by Zed1976** [comment]
Thank you very much . it working now !!! :)
