### ISSUE TITLE
Show address on device feature doesn't work

### ISSUE THREAD

**Issue by MrClottom** [LedgerHQ/app-monero#67]
Using ledger app version 1.6.0
Using Monero GUI version: v0.16.0.0 (Qt 5.9.7)
Monero embedded version: v0.16.0.0

When selecting a subaddress in the receive tab and pressing 'show on device' only the main public address is shown along with the major and minor numbers. If this is a bug on the part of the GUI I could open an issue there.

**Comment by grydz** [comment]
I'm able to reproduce the bug and the fix is in progress.

Thanks!

**Comment by grydz** [comment]
PR https://github.com/LedgerHQ/app-monero/pull/68 should fix the problem.

**Comment by grydz** [comment]
PR https://github.com/LedgerHQ/app-monero/pull/68 has been merged. The fix will be included in version `1.6.1` of the Monero app.
