### ISSUE TITLE
Wrong Device Status: 0x6701 (UNKNOWN), EXPECTED 0x9000 (SW_OK), MASK 0xffff

### ISSUE THREAD

**Issue by kwalikum** [LedgerHQ/app-monero#75]
Windows 10, Monero GUI 0.16.0.0 (Qt 5.12.2)
Ledger Nano S firmware 1.6.0, Monero app 1.6.0

Fully synchronised. Tried restarting everything many times. Tried running as administrator.

Ledger says "Preparing TX" before Monero GUI displays the error.

**Comment by pricead** [comment]
This issue is fixed with Monero CLI 16.0.0.1. The corresponding Monero GUI with the fix should be released soon.

**Comment by grydz** [comment]
> This issue is fixed with Monero CLI 16.0.0.1. The corresponding Monero GUI with the fix should be released soon.

I'm closing the issue.

Please open a new one if you have any trouble with Monero GUI 16.0.0.1.

**Comment by selsta** [comment]
Corresponding GUI is ready and will be released today / tomorrow.

**Comment by kwalikum** [comment]
Confirmed working. Many thanks to all involved!
