### ISSUE TITLE
Error when trying to restore

### ISSUE THREAD

**Issue by Zarovzky** [LedgerHQ/app-monero#78]
Getting this when restoring: Error while finding module specification for 'ledger.monero.seedconv.py' (ModuleNotFoundError: No module named 'ledger')

**Comment by grydz** [comment]
Could you provide the command you typed and in which directory?

**Comment by selsta** [comment]
I think this can be closed, we helped this user on Reddit: https://reddit.com/r/Monero/comments/i72cku/ledger_cannot_conver_to_25_words/

(assuming it is the same user)

**Comment by Alexander1984z** [comment]
> Getting this when restoring: Error while finding module specification for 'ledger.monero.seedconv.py' (ModuleNotFoundError: No module named 'ledger')

**Comment by selsta** [comment]
@Alexander1984z Please follow this tutorial step by step and it should work: https://monero.stackexchange.com/questions/11979/how-to-convert-ledger-seed-to-monero-compatible-seed-on-windows
