### ISSUE TITLE
Garbage displayed after the address with 1.7.2

### ISSUE THREAD

**Issue by DestroyFX** [LedgerHQ/app-monero#82]
I made pictures here : https://imgur.com/a/O4tGUXR

The address show correctly but then after it continue for 1 or 2 pages with garbage.

ledger application monero-dev 1.7.2 installed (I did not notice that bug with 1.6)
Also using latest monero daemon and cli.

**Comment by FabriceDautriat** [comment]
@grydz , can you please take a look ?  Thanks.

**Comment by grydz** [comment]
It should be fixed in the future Monero app 1.7.3.
