### ISSUE TITLE
Unable to create a wallet with Monero GUI: Wrong Device Status 0x6e00

### ISSUE THREAD

**Issue by n-other** [LedgerHQ/app-monero#83]
Hello, 

I'm trying to create a wallet with Monero GUI (0.16.0.3) from my Ledger Nano X device and following error occurs:
failed to generate new wallet: Wrong Device Status: 0x6e00 (SW_CLA_NOT_SUPPORTED), EXPECTED 0x9000 (SW_OK), MASK 0xffff

Ledger Nano firmware is 1.2.4-4
Monero app is 1.6.0

**Comment by pricead** [comment]
What version of the Monero app do you have on your device?

**Comment by n-other** [comment]
Monero app is 1.6.0

**Comment by pricead** [comment]
Apologizes, I see you actually mentioned that in your original post. 

1.6.0 should be working fine with Monero GUI (0.16.0.3). Make sure you don't have any other apps open on your computer that communicate with the Ledger device (such as Ledger Live).

**Comment by pricead** [comment]
Here a link to a thread with the same problem and other possible solutions:
https://www.reddit.com/r/monerosupport/comments/invtqf/failed_to_generate_new_wallet_wrong_device_status/

**Comment by n-other** [comment]
heh, I should have open monero app on the device. it works. thanks!
