### ISSUE TITLE
Only way to recover by seed phrase is to compile app manually?

### ISSUE THREAD

**Issue by mishawagon** [LedgerHQ/app-monero#89]
The GUI doesn't allow for seed phrase backup, it seems only possible with this tool. However this tool can't be used on a ledger where the Monero app was installed via Ledger Live right? It has to be manually compiled and put on the ledger hardware using these tools, right? I'm super confused. I'm testing wallet recovery as a learning exercise and have completely hit a wall on the UX of it all.

**Comment by jonathancross** [comment]
@mishawagon Did you find out more about this?
Adding documentation / tips for others would be great!

**Comment by pricead** [comment]
Mishawagon is mistaken, this tool in no way requires anything be installed on the device itself, besides the normal Ledger Monero app that you install via Ledger Live. You just run the tool on a PC/Mac/Linux, and it can either work in "offline" mode where you would type your Ledger seed into the PC to get the derived Monero seed, or you can use it in "online" mode, where the seed will be displayed on the device itself, under the menu inside the Monero app.

Instructions are all here: https://github.com/LedgerHQ/app-monero/tree/master/tools/python
