### ISSUE TITLE
Transfer from MyMonero to MoneroApp in Ledger.

### ISSUE THREAD

**Issue by Alioz88** [LedgerHQ/app-monero#92]
Hello !!!

I have an issue with a transfer that i made the 23 March 2021
It was a transfer from MyMonero (Dekstop) to MoneroApp (Ledger Nano X) = approximately 2 XMR
The transactions is successfull on MyMonero but i see no Monero on my Ledger Live.

Did i do something wrong ?

**Comment by johnalanwoods** [comment]
Ledger live doesn't support Monero. You need to use the core wallet.

**Comment by Alioz88** [comment]
> Ledger live doesn't support Monero. You need to use the core wallet.

Whats is the core wallet ? 
I don't know to access this fund now since it doesn't show up on Ledger Live 🤔

**Comment by pricead** [comment]
https://support.ledger.com/hc/en-us/articles/360006352934-Monero-XMR-

You need to download the Monero-GUI, which connects to your device running the XMR app.

**Comment by Alioz88** [comment]
> You need to download the Monero-GUI, which connects to your device running the XMR app.

I have tried to open it with MoneroGUI but when i put my password to open my account the loading screen keep turning but never open the account. I don't know why.

**Comment by pricead** [comment]
> > You need to download the Monero-GUI, which connects to your device running the XMR app.
> 
> I have tried to open it with MoneroGUI but when i put my password to open my account the loading screen keep turning but never open the account. I don't know why.

You need to confirm the export of your view key on the device screen when opening the wallet on Monero-GUI. 

Anyway, this GitHub is for reporting actual bugs with the device's Monero app, and not general user support. I suggest you visit www.reddit.com/r/MoneroSupport if you'd like additional assistance.

**Comment by Alioz88** [comment]
> You need to confirm the export of your view key on the device screen when opening the wallet on Monero-GUI.

How can do i export the view keys and where i find this key ?
I'm really lost with all of this.

**Comment by pricead** [comment]
> > You need to confirm the export of your view key on the device screen when opening the wallet on Monero-GUI.
> 
> How can do i export the view keys and where i find this key ?
> I'm really lost with all of this.

Like I said, this is the wrong place for posting these kinds of user questions.

**Comment by Alioz88** [comment]
> 
> 
> > > You need to confirm the export of your view key on the device screen when opening the wallet on Monero-GUI.
> > 
> > 
> > How can do i export the view keys and where i find this key ?
> > I'm really lost with all of this.
> 
> Like I said, this is the wrong place for posting these kinds of user questions.

Okey, thank you very much.

**Comment by infa-jowoods** [comment]
@Alioz88 you’ll get help at Reddit.com/r/Monero

**Comment by pricead** [comment]
> @Alioz88 you’ll get help at Reddit.com/r/Monero

As I mentioned above, www.reddit.com/r/MoneroSupport is designed for support questions. We try to keep r/Monero clear of those to avoid it from being cluttered.

**Comment by Alioz88** [comment]
> 
> 
> @Alioz88 you’ll get help at Reddit.com/r/Monero

Thank you
